Created a volunteer model and prescribed connections
Alisher24/PetFamily pull request #3
Opened 2024-08-26 15:39 UTC by Alisher24

2024-08-26 17:21 UTC, YADARAN1 requested changes

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Interfaces/IEntityId.cs
> +    public T Id { get; set; }
![image](https://github.com/user-attachments/assets/4c489342-0058-47b6-ad28-a4a89f0f9482)
Должно выглядеть так

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/AssistanceDetail.cs
> +    public Guid Id { get; set; }
Ты уже наследуешься от IEntityId, тебе не надо это писать

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/AssistanceDetail.cs
> +public class AssistanceDetail : IEntityId<Guid>
У Кирилла есть репозиторий, посмотри реализацию там https://github.com/KirillSachkov/sachkov-tech/tree/main/backend

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/AssistanceDetail.cs
> +    public required Pet Pet { get; set; }
Убрать

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/AssistanceDetail.cs
> +    public Guid PetId { get; set; }
Убрать

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/AssistanceDetail.cs
> +    public Guid Id { get; set; }
Слово required убрать у всех свойств

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Pet.cs
> +    public Guid Id { get; set; }
Убрать

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Pet.cs
> +public class Pet : IEntityId<Guid>
Переделать

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Pet.cs
> +    public Guid Id { get; set; }
Слово required убрать у всех свойств

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Pet.cs
> +    public required Volunteer Volunteer { get; set; }
Удалить

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Pet.cs
> +    public Guid VolunteerId { get; set; }
Удалить

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/SocialNetwork.cs
> +public class SocialNetwork : IEntityId<Guid>
Переделать

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/SocialNetwork.cs
> +    public Guid Id { get; set; }
Удалить

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/SocialNetwork.cs
> +    public Guid Id { get; set; }
Слово required убрать у всех свойств

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/SocialNetwork.cs
> +    public Guid VolunteerId { get; set; }
Удалить

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Volunteer.cs
> +public class Volunteer : IEntityId<Guid>
Переделать

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Volunteer.cs
> +    public Guid Id { get; set; }
Убрать

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Volunteer.cs
> +    public Guid Id { get; set; }
Слово required убрать у всех свойств

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Volunteer.cs
> +    public List<SocialNetwork> SocialNetworks { get; set; } = [];
public IReadOnlyList<SocialNetwork> SocialNetworks { get; private set; } => _socialNetwork;

private readonly List<SocialNetwork> _socialNetwork = []

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Volunteer.cs
> +    public List<SocialNetwork> SocialNetworks { get; set; } = [];
Cо всеми листами делаешь так

2024-08-26 17:21 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Pet.cs
> +    public Guid Id { get; set; }
И добавить всем свойствам private set

2024-08-27 11:03 UTC, Asasen1 requested changes

2024-08-27 11:03 UTC, Asasen1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Volunteer.cs
> +    private Volunteer(Guid id,
Если приватный, то где фабричный метод?

2024-08-27 11:03 UTC, Asasen1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Pet.cs
> +    public Pet(Guid id) : base(id) { }
Приватный

2024-08-27 11:03 UTC, Asasen1 commented on PetFamily.Backend/src/PetFamily.Domain/Models/Shared/FullName.cs
> +public record FullName(string FirstName, string LastName, string Patronymic);
Сделай Patronymic nullable

2024-08-27 11:15 UTC, Asasen1 approved these changes

2024-08-27 11:16 UTC, merged