Id b 12
Alisher24/PetFamily pull request #30
Opened 2024-10-07 21:20 UTC by Alisher24

2024-10-07 22:09 UTC, Alisher24 commented
Нормально что методы с использованием readDbContext я использую в репозиториях и кидаю к ним readDbContext через слой aplication?

2024-10-08 11:44 UTC, KirillSachkov requested changes
Ответил насчёт readdbcontext, всё остально хорошо

2024-10-08 11:44 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Infrastructure/Repositories/SpeciesRepository.cs
> +            return Errors.General.ValueIsBeingUsedByAnotherObject($"Species with id: {species.Id.Value}");
Нельзя использовать readdbcontext в репозитории, эта проверка - это часть бизнес логики, её обязательно нужно использовать в application слое, и вызов readdbcontext тоже нужно перенести туда

2024-10-09 08:23 UTC, KirillSachkov approved these changes

2024-10-09 11:14 UTC, merged